"""initial migration

Revision ID: e1900faa1687
Revises: 
Create Date: 2026-04-02 23:43:20.323439

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e1900faa1687'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('description', sa.String(length=140), nullable=False),
    sa.Column('role', sa.String(length=45), nullable=False),
    sa.Column('image', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('id_UNIQUE'))
        batch_op.drop_index(batch_op.f('name_UNIQUE'))

    op.drop_table('agents')
    with op.batch_alter_table('maps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('id_UNIQUE'))

    op.drop_table('maps')
    with op.batch_alter_table('weapons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('id_UNIQUE'))
        batch_op.drop_index(batch_op.f('name_UNIQUE'))

    op.drop_table('weapons')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weapons',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('damage1', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('damage2', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('damage3', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('cost', mysql.VARCHAR(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('weapons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('name_UNIQUE'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('id_UNIQUE'), ['id'], unique=True)

    op.create_table('maps',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('coordenates', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('sitesnumber', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('maps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('id_UNIQUE'), ['id'], unique=True)

    op.create_table('agents',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=140), nullable=False),
    sa.Column('role', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('image', mysql.VARCHAR(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id', 'image'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('name_UNIQUE'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('id_UNIQUE'), ['id'], unique=True)

    op.drop_table('agent')
    # ### end Alembic commands ###
